// apps/microapp-vue2/src/App.vue
<script setup>
import { ref, onMounted } from 'vue'

const msg = ref('Vue Micro App 2')
const globalState = ref(null)

onMounted(() => {
  if (window.__WUJIE_GLOBAL__) {
    globalState.value = window.__WUJIE_GLOBAL__.globalState
  }
})

function incHost() {
  if (window.__WUJIE_GLOBAL__ && window.__WUJIE_GLOBAL__.inc) {
    window.__WUJIE_GLOBAL__.inc()
  }
}
</script>

<template>
  <div class="app">
    <h1>{{ msg }}</h1>
    <p>This is a second Vue micro application</p>
    <div v-if="globalState">
      <p>Host user: {{ globalState.user }}</p>
      <p>Host count: {{ globalState.count }}</p>
      <button @click="incHost">Increment host count</button>
    </div>
  </div>
</template>

<style scoped>
.app {
  padding: 20px;
}
</style>

// apps/microapp-react/src/App.jsx
import React, { useEffect, useState } from 'react'

function App() {
  const [globalState, setGlobalState] = useState(null)

  useEffect(() => {
    if (window.__WUJIE_GLOBAL__) {
      setGlobalState(window.__WUJIE_GLOBAL__.globalState)
    }
  }, [])

  function incHost() {
    if (window.__WUJIE_GLOBAL__ && window.__WUJIE_GLOBAL__.inc) {
      window.__WUJIE_GLOBAL__.inc()
      // trigger re-read
      setGlobalState({ ...window.__WUJIE_GLOBAL__.globalState })
    }
  }

  return (
    <div className="app">
      <h1>React Micro App</h1>
      <p>This is a React micro application</p>
      {globalState && (
        <div>
          <p>Host user: {globalState.user}</p>
          <p>Host count: {globalState.count}</p>
          <button onClick={incHost}>Increment host count</button>
        </div>
      )}
    </div>
  )
}

export default App
